### ISSUE TITLE
SDV Parametrization: CSV file to TfRecord

### ISSUE THREAD

**Issue by snoiarao** [zgojcic/3DSmoothNet#19]
When computing the SDV grids using the included 3DSmoothNet executable (super helpful tool, thanks for including!), I noticed it saves the output into a CSV file. I am trying to fine tune the network using my own data, but saveDataToTFrecordsExample.py reads in a numpy array. I am not able to easily convert the CSV into a numpy array which seems necessary to convert the training data to tfrecord format. Is there a way to change the output file format? Thanks so much!

**Comment by zgojcic** [comment]
Hi, 

could you maybe provide more information what the difficulties in converting the csv to np.arrray are? You could just use np.genfromtxt() or some other function (e.g. pandas)

**Comment by snoiarao** [comment]
filepath = location of saved SDV CSV file from 3Dsmoothnet executable

np.genfromtxt(filepath, delimiter=',') is able to load the file without throwing an error, but the numpy array is empty "UserWarning: genfromtxt: Empty input file"
pd.read_csv(filepath) also loads the file but df.head() suggests the file is empty: "<bound method NDFrame.head of Empty DataFrame"

I have checked that the file exists in the correct filepath, is non empty and 30MB in size, and is too large to open with my ubuntu excel software. 

Do you know what the issue might be? Perhaps I am not understanding the format of the data saved in each CSV file. Please let me know if you have any insights!

**Comment by caifazhou** [comment]
thank you for your updates. 

can you try to load the csv file using `pandas` in the way of:
x = pd.read_csv(filepath=csv_path, header=None).values
because by default `pandas` assumes that there is a header. But it should have problem. 

Also for open the csv file to have a eye-check, you can use some txt editor (e.g., notepad++, sublime or atom). Excel does not work out for large csv file.

If you still have difficult to read the csv, please share the file with us. Send me the csv file per E-mail.

**Comment by snoiarao** [comment]
Thanks for the suggestion! I was able to open the CSV file with Notepad++ and have realized the issue. While the demo SDV file has lots of content, my SDV file (direct output from 3DSmoothNet with default parameters) is 30MB of "NUL" content. It seems that no SDV grids are being computed at all.
My data consists of indoor RGBD point clouds taken from a Kinect sensor. I have index files consisting of 2000 key point indices for each point cloud. When I send it to ./3DSmoothNet, the parameters are successfully read in ("Config parameters successfully read in!!") for each .ply + .txt pair; it takes about 10 minutes for LRF computation and 1 minute for SDV computation before saving the results to a CSV. Do you have any idea why the SDV files are empty? Any insight would be super helpful! Thanks so much.

**Comment by zgojcic** [comment]
It is very hard to say like this what the problem could be but the time needed for LRF seems quite long. Could you maybe just send us the file together with the keypoints indices and parameters that you have used and then we will have a look.

**Comment by snoiarao** [comment]
I understand, thank you for offering to take a look! The files are too large to attach via github; is there an email that I can send to?

**Comment by zgojcic** [comment]
You can send it to zan.gojcic@geod.baug.ethz.ch.

**Comment by rui2016** [comment]
So what was the conclusion here?

**Comment by MaryAnnZ** [comment]
I am also curious about the solution of this issue

**Comment by MaryAnnZ** [comment]
In my case it was a scaling issue. I have multiple point clouds of the same objects scanned by different scanners and I was trying to register them (whereas the files for registering were created by the same scanner). It worked for my LiDAR scanner but failed for the kinect, the csv files were filled with `null`. Visualizing the point clouds in Cloud Compare I saw that the kinect files are ~100X bigger than the LiDAR files.
I didnt check the 3DSmoothNet code in detail I assume they do use some kind of normalization, but I can also imagine that their normalozation fails because the kinect point cloud is actually just 2,5D and not 3D. Im not sure since Im not an expert in this topic. But scaling down the kinect data helped, and the csv files are written as intendeds
