### ISSUE TITLE
Script for input parametrization for 3DMatch dataset

### ISSUE THREAD

**Issue by jingnanshi** [zgojcic/3DSmoothNet#22]
Hi,

First of all, thank you guys for sharing this excellent work online. I'm in the process of reproducing the results mentioned in the paper using your MATLAB script, and noticed that there's no script for running input parametrization on the 3DMatch dataset. 

Is there a chance for you guys to provide such a script? 

Thanks in advance!

**Comment by zgojcic** [comment]
Hi Jinngnan, 

I am not sure I completely get you question. 

In order to reproduce the results on 3DMatch data set you would have to: 
- Download the point clouds and keypoints from the link we provided
- For all fragments infer the SDV voxel grids using the provided c++ code
- Infer the 3DSmoothNet descriptors using the provided model and python code 
- Then run the matlab codes which only serve to load the descriptors compute the nearest neighbors and output the evaluation metrics. 

If you have any questions to each of those steps please let me know. I could probably also provide you the 3DSmoothNet descriptors or even log files used by the matlab script if that would be of interest. We did not include it here because of the space constraints.

Best

Zan

**Comment by jingnanshi** [comment]
Hi Zan,

Thank you for your swift reply!

I was referring to the second step (input parametization to SDV voxel grids). I am currently just writing a python script to run the c++ code over all the fragments in the 3DMatch dataset, and I'm just wondering whether there's a script somewhere in the repo that does that.

Best,

**Comment by zgojcic** [comment]
Hi Jingnan, 

sadly there is no such script as before the CVPR deadline we were working with the .txt configuration files and have later changes the code to use the command line arguments. 

You should however be able to reuse part of the demo code and then just loop over all the scenes and all the fragments withing each scene. 

Hope this helps, otherwise let me know.

Best

Zan

**Comment by jingnanshi** [comment]
Hi Zan,

Thanks for your clarification! Yes that's what I'm doing right now. After I finish & making sure everything works together I'll submit a pull request. Closing this issue now.

Thanks again!

Best,
Jingnan
